
package com.example.marketintelligence.data.model

// --- AI Engine Inputs & Outputs ---

enum class MarketRegime {
    TRENDING_BULLISH,
    TRENDING_BEARISH,
    RANGING_HIGH_VOLATILITY,
    RANGING_LOW_VOLATILITY,
    UNDEFINED
}

// Represents a complete, actionable trade signal generated by the AI
data class AiTradeSignal(
    val underlyingSymbol: String,
    val strategyName: String,
    val marketRegime: MarketRegime,
    val optionLegs: List<OptionLeg>,
    val entryPrice: Double, // Net premium
    val target: Double,
    val stopLoss: Double,
    val confidenceScore: Double,
    val riskParameters: RiskParameters
)

data class RiskParameters(
    val positionSize: Int, // Number of lots
    val capitalRequired: Double,
    val marginRequired: Double,
    val maxLoss: Double
)
